version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - ENV=development
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
