version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - ENV=development
      - LEADER_LEASE_DURATION=30
      - MONGODB_URI=mongodb://nightblood.local:27017
      - DB_NAME=Swarmer
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "2"
          memory: 50M
      restart_policy:
        condition: on-failure
