version: '3.8'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - ENV=development
      - LEADER_LEASE_DURATION=30
      - MONGODB_URI=mongodb://nightblood.local:27017
      - DB_NAME=Swarmer
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "2"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - swarmer-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 15s


networks:
  swarmer-network:
    driver: bridge

 
